### PR TITLE
Fix cutoff shadow on wifi options buttons

### LINKED ISSUE #153: Cutted shadow under button in wifi settings
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
 ```
corsseir@ltc0:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.04 LTS
Release:	18.04
Codename:	bionic

corsseir@ltc0:~$ apt policy libgtk-3-0
libgtk-3-0:
  Installed: 3.22.30-1ubuntu1
  Candidate: 3.22.30-1ubuntu1
  Version table:
 *** 3.22.30-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

Gnome Shell

corsseir@ltc0:~$ head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css
/***************************
 * Pop!_GTK+ Version 3.1.0 *
 ***************************/
**Related Application and/or Shell theming (or name of widget)**
---

**Actual issue**
Cutted shadow on left and right side under button in wifi settings:

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**
OK

**Other Note (feature-request, question, etc...)**

### PR DESCRIPTION
**Pull request by isantop**
Adds a small margin to button.image-button.circular's in gnome control center. This keeps the shadow from being clipped. Fixes #153

### CODE REVIEW

**Comment by jackpot51** [comment]
I was unable to see a difference with this installed vs not installed.

**Comment by brs17** [comment]
With my `apt policy pop-gtk-theme` returning the installed version "...~38270ae" I too do not see a difference.

**Comment by isantop** [comment]
@brs17 Can you include a screenshot showing the clipped shadows in the WiFi settings dialog? You will need to be connected to WiFi and have the small circular settings button present.

**Comment by brs17** [comment]
@isantop Here you go: 
pr157

**Comment by isantop** [comment]
@brs17 The selector had an extra e. The problem is now fixed.

**Pull request merged**
