### PR TITLE
Installer style

### PR DESCRIPTION
**Pull request by isantop**
This PR adds app-specific styling for the Installer. It themes the diskbar in a Pop style, using colors from the color-palette file.

screenshot from 2018-04-06 15-45-52

### CODE REVIEW

**Comment by cassidyjames** [comment]
Depends on https://github.com/pop-os/installer/pull/41 for testing

**Comment by jackpot51** [comment]
@cassidyjames can you test this with the installer built from the `remove-css` branch? I would like to merge the theme change before merging the installer CSS removal change

**Comment by cassidyjames** [comment]
@isantop or I will need to update this to match the expected API, which should simplify it significantly; it's using the normal storage bar styles and just needs the filesystem colors added.

**Comment by jackpot51** [comment]
This works correctly when paired with the latest installer

**Pull request merged**
