### PR TITLE
Elementary colors

### LINKED ISSUE #236: Ship elementary palette definitions
elementary is leaning more on the palette color definitions in the stylesheet to keep the colors in sync across the OS. What this means for Pop!_OS is that without the color palette defined, you'll start seeing funkiness like this:

image

instead of this:

appcenter-categories-after 2x

### PR DESCRIPTION
**Pull request by isantop**
Does the same thing as #237 but does it with pop-y colors and with the correct defines. 

Fixes #236 
Closes #237

### CODE REVIEW

**Comment by brs17** [comment]
The "System" category is now more difficult to read. I also noticed that the Finance icon is missing. screenshot from 2018-12-19 10-34-37

**Comment by isantop** [comment]
The finance icon will require an icon theme update, or having the elementary icons installed (since that's set as a fallback for the Pop icon theme.

I recommend the System category be fixed in the Pop_Shop CSS, since that's the Pop version of the color they list. The alternative would be to take the elementary colors directly and use those.

**Comment by brs17** [comment]
The latest commit makes all of the categories legible. :+1: 

> The finance icon will require an icon theme update, or having the elementary icons installed (since that's set as a fallback for the Pop icon theme. In either case, it's not an issue with the gtk-theme.
Alright, so I will wait to see a pr for the icon theme that fixes this before approving this pr.

**Comment by isantop** [comment]
@brs17 Icon theme pull-request has been added.

For the record, I don't think this pull request depends on that PR. This PR adds a feature which happens to be used by pop-shop, but which is also useful outside of that context. For example, with @cassidyjames 's Palette application, this PR will fix severe usability issues that prevent the application from being usable at any real level. If the Shop PR requires this icon, then it should depend on the icon theme, rather than creating a huge chain of PR dependencies where each item isn't really related to each other, but the top level PR is dependent on all of them.

The icon theme PR fixes the issue with the Shop PR, ergo it's the shop that depends on it. It doesn't do anything to help or hinder this one, so this one is totally separate.

**Comment by brs17** [comment]
You're correct, this pr does not depend on https://github.com/pop-os/icon-theme/pull/43.

**Comment by brs17** [comment]
Having second thoughts now on the readability of some of the categories in Pop!_Shop with these changes...in particular the `Communication` category as well as the `Audio` category. 

These categories are a bit difficult to read: 
screenshot from 2018-12-19 14-37-13

**Comment by isantop** [comment]
They have the same contrast ratios as the colors in the elementary theme. If that's an issue, then it should be corrected in the Pop_Shop categories.css file.

**Comment by isantop** [comment]
pop-os/shop#111 has been opened against the Shop branch in pop-os/shop#107 which should address contrast concerns.
screenshot from 2018-12-21 11-41-14

**Pull request merged**
