### PR TITLE
Pin Pop PPA with a lower priority

### PR DESCRIPTION
**Pull request by honnix**
This is to prevent accidentally installing/upgrading other packages from this PPA.

### CODE REVIEW

**Comment by honnix** [comment]
@ids1024 Not sure whether this makes sense. PTAL, thanks!

**Review by isantop — CHANGES_REQUESTED** [review]
I'm not sure this is the advice we should be giving for this. The official advice right now is to only add the Pop PPA on a Pop_OS installation (where realistically it should already be installed). The current README does not indicate that as clearly as would be ideal, but adding the PPA does present the scary warning message:

```
A repository for all Pop!_OS software components.

WARNING: This PPA is for Pop!_OS, and it may cause breakage on other Ubuntu-based OS's. Use of this repository on non-Pop_OS installations is at your own risk!
```

Pinning can help, but can also create issues if a particular version of a package is installed from the wrong repository (e.g. via a dependency). This situation seems very likely to me to result in a [FrankenDebian](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian) (or a FrankenBuntu, more accurately). We should instead be suggesting to users to install from source code instead.

**Comment by honnix** [comment]
@isantop Thanks for the quick reply and explaining. I see the problem, especially on `pop-gtk-theme`, and I agree installing from source code should be instead suggested.

**Comment by honnix** [comment]
I actually had to do the following to make it right. Otherwise some packages will be pulled from other distributions.

```
sudo tee <<EOF /etc/apt/preferences.d/system76-pop-pin >/dev/null
Package:  *
Pin: release o=LP-PPA-system76-pop
Pin-Priority: 400

Package:  pop-theme
Pin: release o=LP-PPA-system76-pop
Pin-Priority: 600

Package:  pop-gnome-shell-theme
Pin: release o=LP-PPA-system76-pop
Pin-Priority: 600

Package:  pop-gtk-theme
Pin: release o=LP-PPA-system76-pop
Pin-Priority: 600

Package:  pop-icon-theme
Pin: release o=LP-PPA-system76-pop
Pin-Priority: 600

Package:  pop-sound-theme
Pin: release o=LP-PPA-system76-pop
Pin-Priority: 600
EOF
```

I tried building from source, but couldn't get shell theme work.

**Pull request closed without merging**
