### PR TITLE
Rework storage bars

### PR DESCRIPTION
**Pull request by cassidyjames**
Reworks how storage bars are styled so we shouldn't have as much special casing for the installer.

- Pulls the partition types into the stock storage bar styles, how we plan to do it in elementary stylesheet
- Keeps borders, padding, etc. the same in normal storage bars and the partitions
- Re-structures the style to lean a little more on SCSS to keep things tidy

@isantop mentioned we might want to only have borders on filesystems instead of all fill-blocks. That can be updated if requested, but the rest of the restructuring is valuable to clean things up and keep it API-compatible with upstream.

### CODE REVIEW

**Comment by cassidyjames** [comment]
Granite Demo:

image


Installer:

image

**Comment by cassidyjames** [comment]
For comparison, elementary stylesheet.

Granite Demo:
image

Installer (missing the specific filesystem colors for now):
image

**Comment by isantop** [comment]
@cassidyjames This looks fine to me, but we need to round the borders of the `:last-child` to make sure a full disk doesn't have square corners on the right and round ones on the left.

**Comment by cassidyjames** [comment]
@isantop it does in fact have the rounded corners on the last child, it's just not obvious in my screenshots because there was an explicit "unused" block at the end of the bars at the time.

**Comment by isantop** [comment]
@cassidyjames Does this still remain relevant in the current v4 branch? The new storage bar styling should be much cleaner and incorporates filesystem styling for the disk bar.

**Comment by cassidyjames** [comment]
@isantop I have no idea. I'd say close this and we can revisit it if there's something to revisit.

**Pull request closed without merging**
