### PR TITLE
change accent color on text to pink #FE00A3

### PR DESCRIPTION
**Pull request by KyroSx**

### CODE REVIEW

**Comment by isantop** [comment]
What's the rationale behind this change? As near as I can tell this will make all of the colors pink instead of blue, which does not match our branding guidelines.

**Comment by KyroSx** [comment]
> What's the rationale behind this change? As near as I can tell this will make all of the colors pink instead of blue, which does not match our branding guidelines.

OMG I MESSED UP!!!
I thought I was Pull requesting to my custom repository;
I'm horrible with git :cry:

**Comment by leviport** [comment]
No worries lol, it happens

**Comment by KyroSx** [comment]
> That's a GitHub issue, they automatically select upstream branches. I've done the exact same thing before on projects with Pop, actually!

I enjoy the popOS theme, I also like a lot the Pink color, then I decided to try making my custom gtk-theme (was my first attempt).
So after I made the changes, commit, then PR, but I don't know what has happened. I was confused.

Bad luck :four_leaf_clover: .

**Pull request closed without merging**
