### PR TITLE
Upstream compliant theming

### PR DESCRIPTION
**Pull request by isantop**
It is expected that 19.10 will ship with the new Adwaita-based Pop theme to increase compatibility with GNOME applications and reduce bugs and breakages. This new codebase represents this work to produce a "compatible" theme which still presents a distinctive Pop identity to the OS. 

Architectural changes:
* This theme is based on the Ubuntu Yaru theme, which brings in the GNOME Shell and GTK Themes under one basket. It includes a light and a dark GNOME Shell theme which will be built automatically and can be set up to automatically switch when the dark theme is selected, pending this functionality in GNOME Shell.
* Built with Meson instead of make. 
* Includes a Sound theme from Yaru (which may or may not be selected by default, and can be set as such in `pop-default-settings`
* Retains the current separated Icon theme.

Visual Updates
* A widely simpler appearance. Pop is still rather flatter than Adwaita, but retains much of its padding and sizing.
* Reduced reliance on shadows for element separation, as this has a tendency to break many things.
* More contrast-compliance in many respects, particularly with the dark theme, which helps ensure usability for all users.
* Brighter, more visible colored backgrounds in the dark theme, as this helps aid contrast and reduce optical vibrations of heavily saturated colors against dark backgrounds.

Current TODOs with this Theme:
- [x] Documentation updates, including new or removed screenshots from the README.
- [x] Documentation updates with build instructions.
- [x] Creating a `disco`-compatible testing branch to allow employees to dogfood the new theme and provide feedback about visuals and design. 
- [x] Moving some style changes from `_common.scss` to `_tweaks.scss`. This should not affect the appearance of the theme.
- [x] Dark theme list bar selected text backdrop is very low-contrast
- [x] Investigate Nautilus list view outline issue.

### CODE REVIEW

**Comment by isantop** [comment]
Please be aware that checkboxes in pop-os/repoman are too-close together with this theme. This is fixed in pop-os/repoman#20

**Comment by brs17** [comment]
Documentation updates should also include replacing the build instructions involving `make`.

**Comment by brs17** [comment]
Will there be slim variations for these themes?

**Comment by brs17** [comment]
On 19.10 where I have installed the appropriate .debs as provided I am seeing odd overlay/padding on the system menu as well as the "notification menu"(not sure of proper name for it). I see this in both the normal theme and dark theme.

Screenshot from 2019-09-24 07-40-24
Screenshot from 2019-09-24 07-40-44
Screenshot from 2019-09-24 08-21-32
Screenshot from 2019-09-24 08-21-38

This is the configuration I have in gnome-tweaks:

Screenshot from 2019-09-24 08-15-24

**Comment by brs17** [comment]
Not sure if it is intentional, but the column selections ("Name", "Size", "Modified", etc) in nautilus are the exact same color as the background. This may make it unclear that the headers are selectable.
 
Screenshot from 2019-09-24 07-48-20

This also appears to be the case in the dark theme as well.

**Comment by WatchMkr** [comment]
Quick notes - stuff to cover with Kate:

- The top bar feels too tight
- Bad contrast on un-focus windows (side bars in particular but also select a file in nautilus and unfocus the window).
- Shell calendar menu text hierarchy feels off (today's month, day, year feel too small). Would love to remove year here if possible. Otherwise, let's take a look at what we can do to improve the sizes.
- Not keen on the arrow pointing to the clock and user menu.

**Comment by isantop** [comment]
@brs17 That is a side effect the the `Pop-testing` theme installation, and doesn't happen when the Pop theme is upgraded to the new version. 

@WatchMkr WRT:

> Not keen on the arrow pointing to the clock and user menu.

This is actually a lot more consistent with GTK, where popovers also use the arrow. I think a large part of what makes them not so great is the aforementioned bug with the -testing theme installation. On the actual installed version, the effect works a lot better and it helps provide a visual hierarchy for where the popup is coming from. I think we should wait until it's easier to test with the way that will actually look before we make a final decision on that. 

One important note is that the visual glitch is caused by a bug in the _current_ Pop shell theme directly related to removing those arrows. When the system theme doesn't use the arrows, and you select a shell theme that does, it creates that issue. Keeping the arrows prevents this sort of glitch and ensures that the Pop theme doesn't break other themes.

**Comment by isantop** [comment]
> Will there be slim variations for these themes?

@brs17 That might be possible, although the Slim themes will cause breakage with apps because of padding changes.

**Comment by brs17** [comment]
> > Will there be slim variations for these themes?
> 
> @brs17 That might be possible, although the Slim themes will cause breakage with apps because of padding changes.

:+1: If that is the case, we will want to remove the `Slim` toggle from gnome-control-center.

**Comment by isantop** [comment]
Updated dark theme selected item foreground color:

Screenshot from 2019-09-24 10-25-16

**Comment by WatchMkr** [comment]
@isantop I prefer the non-arrow drop down in the shell because there are three things in the user menu but it's pointing to one thing... kind of. It is nice in other places - such as the settings menu on a printer. Open to either but that's my thinking.

**Comment by WatchMkr** [comment]
Pop!_Shop doesn't show the badge when there are updates. I think it's better. The badge doesn't add much for the user and has looked out of place for a while.

**Comment by isantop** [comment]
@WatchMkr I believe the badge looking out of place is due to a bug in the Pop_Shop application CSS. Having the badge does serve an important use, as it notifies the user that there are updates available. The badge should however be styled to fit in with Pop.

**Comment by isantop** [comment]
I'm also still seeing the badge, but it doesn't show consistently, which might be due to bugs in Pop_Shop itself.

**Comment by isantop** [comment]
@brs17 Nautilus list-view header borders

Screenshot from 2019-09-24 10-48-06

**Comment by WatchMkr** [comment]
Take a closer look at the orange used in the light theme with Kate. Dark theme colors come across as smooth and fitting. Taffy instead of hard candy. Light theme colors (especially orange) look saturated. Hard candy instead of taffy.

**Comment by isantop** [comment]
@WatchMkr updated Debs with the latest fixes:

[pop-testing.zip](https://github.com/pop-os/gtk-theme/files/3649732/pop-testing.zip)

**Comment by brs17** [comment]
dpkg errors still cause failure to add the new theme via the upstream-compliant staging repository.

Errors when trying to add the theme:
```
system76@pop-os:~$ sudo apt upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  gir1.2-mutter-4 libdouble-conversion1 libebook-contacts-1.2-2 libecal-1.2-19
  libgnome-desktop-3-17 libip6tc0 liblirc-client0 libmessaging-menu0
  libmutter-4-0 libmysqlclient20 libpoppler87
  libreoffice-avmedia-backend-gstreamer libtagc0 libvpx5 multiarch-support
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  pop-gnome-shell-theme pop-gtk-theme
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 528 kB of archives.
After this operation, 2,043 kB disk space will be freed.
Do you want to continue? [Y/n] 
Get:1 http://apt.pop-os.org/staging/upstream-compliant eoan/main amd64 pop-gtk-theme all 5.0.0~1569615259~19.10~d3d09d6 [416 kB]
Get:2 http://apt.pop-os.org/staging/upstream-compliant eoan/main amd64 pop-gnome-shell-theme all 5.0.0~1569615259~19.10~d3d09d6 [113 kB]
Fetched 528 kB in 1s (378 kB/s)                 
(Reading database ... 234259 files and directories currently installed.)
Preparing to unpack .../pop-gtk-theme_5.0.0~1569615259~19.10~d3d09d6_all.deb ...
Unpacking pop-gtk-theme (5.0.0~1569615259~19.10~d3d09d6) over (4.1.4~1560290633~
19.10~f75e86a) ...
dpkg: error processing archive /var/cache/apt/archives/pop-gtk-theme_5.0.0~15696
15259~19.10~d3d09d6_all.deb (--unpack):
 trying to overwrite '/usr/share/themes/Pop/gnome-shell/gnome-shell.css', which 
is also in package pop-gnome-shell-theme 4.0.12~1559836915~19.10~d27d536
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../pop-gnome-shell-theme_5.0.0~1569615259~19.10~d3d09d6_all
.deb ...
Unpacking pop-gnome-shell-theme (5.0.0~1569615259~19.10~d3d09d6) over (4.0.12~15
59836915~19.10~d27d536) ...
Errors were encountered while processing:
 /var/cache/apt/archives/pop-gtk-theme_5.0.0~1569615259~19.10~d3d09d6_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by brs17** [comment]
Installing it still seemed to work just fine with an `apt insall pop-gtk-theme`. :confused:

**Comment by brs17** [comment]
The `Cancel` button on the login screen is the exact same color as the background of the login page and therefore the only part of the button that is really visible is the text itself.

**Comment by brs17** [comment]
In GNOME Calendar, when creating a new event, the label which shows which calendar the event will be added to, might be too low contrast.

Notice where it says "Personal" in the top bar.

19.10:
calendar-text-contrast

19.04:
calendar

**Comment by brs17** [comment]
> @brs17 Nautilus list-view header borders
> 
> Screenshot from 2019-09-24 10-48-06

This does look better.

I do notice that the text color of the headers looks very light, almost as if they are deactivated/not clickable. Might a slightly darker font be better here?

**Comment by brs17** [comment]
Per offline discussion, let's make sure that updates on a system work well...let's potentially solve this issue https://github.com/pop-os/gtk-theme/pull/322#issuecomment-536244863 and then I'll give the :+1: and we can merge it to master_eoan. From there, individual issues will be created for issues found. 

This already looks really good and I think a lot of people will love it!

**Comment by isantop** [comment]
https://github.com/pop-os/gtk-theme/pull/322#issuecomment-536244863 has been addressed, and everything appears to work. The theme is correctly updated and applied on both upgrades and new installations.

**Comment by isantop** [comment]
@brs17 I already created issues for the other outstanding notes.

**Comment by brs17** [comment]
I still got a warning, but after a reboot, the theme seems to be working just fine.

Screenshot from 2019-09-30 18-41-43

**Comment by isantop** [comment]
@brs17 What do you get for output of `ls -R /usr/share/themes/Pop/gtk-3.22`

**Pull request merged**
