### PR TITLE
Sync 3.38

### PR DESCRIPTION
**Pull request by isantop**
Pulls in changes in the base theme from Adwaita 3.38

### CODE REVIEW

**Comment by isantop** [comment]
Note: Since the `master` branch of this repo currently only builds for groovy, the failed bionic build should not be a problem. It appears to be differences related to sassc

**Comment by isantop** [comment]
Testing should just be a factor of ensuring there are no apparent regressions in either the GTK or GNOME Shell themes.

**Comment by jacobgkau** [comment]
The only difference I've spotted so far is when opening icon grid folders, their titles are faded after the change. Before:

folder-title-before

After:

folder-title-after

That seems like it could be a regression. It looks like the `color` line was removed from the `.folder-name-label` class in `_app-grid.scss`, which I assume has something to do with it.

**Comment by isantop** [comment]
I agree with that assessment. I'll update that.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
That fixed the label when viewing the folder. I am also seeing a regression when editing folder names, which was not fixed by that change. It only seems to affect the light theme. Before:

light-before-1

light-before-2

After:

light-c-after-1

light-c-after-2

**Comment by isantop** [comment]
Actually, it appears they were being taken from the non-editing mode. Since the entry is light-colored, the light text blended in.

**Review by jacobgkau — APPROVED** [review]
Looks good now. Haven't been able to find any other regressions, all the GTK widgets look normal.

**Pull request merged**
