### PR TITLE
Pop Sound Theme

### LINKED ISSUE #390: Loss of sound volume notification affects accessability
User of Orca screen reading software called in with question on why we removed the sound on volume change notification.

### PR DESCRIPTION
**Pull request by isantop**
This PR adds the new Pop_OS-designed sound theme. It adds a bunch of new sounds that help to enhance the user experience, increase a11y, and provide unique auditory branding of Pop_OS.

The overall profile of the notes used within the theme were developed with guidance from Kate in design, to ensure that the sounds fit with the Pop_OS branding. 

Fixes #390 by adding a pop-branded volume change notification sound.

### CODE REVIEW

**Comment by brs17** [comment]
I see the list of sounds added in the README, @isantop could you please detail how one would hear each of these sounds in Pop!_OS? Thank you.

**Comment by isantop** [comment]
@brs17 It was discovered after creating the sounds that many of them are not used in GNOME. This should probably be fixed in GNOME as many of these represent usability issues. 

### Alerts 
battery-low - Allow battery to reach low level

### Notifications
device-added - plug in a USB drive
device-removed - unplug a USB drive
power-plug > power-unplug

### Actions
bell - press Backspace in a blank GTK Entry
audio-volume-change - Change volume.

Sounds not listed here don't currently have a trigger in GNOME Shell or other applications.

**Comment by leviport** [comment]
I started taking a look at this, and here is what I'm finding so far:

- I think there is an issue with power plug/unplug. Plugging in my AC adapter plays `power-plug.oga`, but unplugging my AC adapter plays the default 'click-click' sound. I noticed a `power-unplug.oga` that is just a symlink to `power-plug.oga`, so maybe the issue lies there. I also wonder if making the two use the same sound is desirable since they used to be two different sounds before.

- Related to the point above, the low battery alert sound works great, but the `power-unplug-battery-low.oga` sound doesn't seem to be working. When my machine was below 10% battery and I unplugged my power adapter, I heard the `battery-low.oga` sound and the default 'click-click' power adapter unplug sound being played at the same time. At the very least, those two sounds shouldn't play simultaneously.

- I found two sounds: `message.oga` and `message-new-email.oga` that sound almost exactly the same as `device-added.oga`. I don't think they should make the same sound, but since the message sounds don't play currently, I wouldn't consider it blocking. The message sounds can be changed later if we decide it needs to be.

- `camera-shutter.oga` does not play when I take a screenshot. Instead I still hear the default sound which sounds like a film camera with an automatic film advance. Could just be another one of the Gnome sound trigger bugs.

- Bell sound is good. 

- Volume up/down/mute sound is good.

- Device add & device remove sound very good to me, but I will point out their similarity to the Windows 7 device add / remove sound effects (example here: https://youtu.be/vJmeYfbP0HU?t=45 ). This was already discussed and it sounds intentional, but I still thought it was worth pointing out.

**Comment by isantop** [comment]
I'm not getting either of the power-plug sounds on my machine, so I think there is a bug in whatever code is triggering those to play.

**Comment by isantop** [comment]
> I started taking a look at this, and here is what I'm finding so far:
> 
> * I think there is an issue with power plug/unplug. Plugging in my AC adapter plays `power-plug.oga`, but unplugging my AC adapter plays the default 'click-click' sound. I noticed a `power-unplug.oga` that is just a symlink to `power-plug.oga`, so maybe the issue lies there. I also wonder if making the two use the same sound is desirable since they used to be two different sounds before.
> * Related to the point above, the low battery alert sound works great, but the `power-unplug-battery-low.oga` sound doesn't seem to be working. When my machine was below 10% battery and I unplugged my power adapter, I heard the `battery-low.oga` sound and the default 'click-click' power adapter unplug sound being played at the same time. At the very least, those two sounds shouldn't play simultaneously.

I'm not able to get any of the power-related sounds to trigger on my machine, so I think there may be a bug in the code that's triggering them to play. 

> * I found two sounds: `message.oga` and `message-new-email.oga` that sound almost exactly the same as `device-added.oga`. I don't think they should make the same sound, but since the message sounds don't play currently, I wouldn't consider it blocking. The message sounds can be changed later if we decide it needs to be.

Three notes on the new-message seemed excessive and potentially annoying, but perhaps going with one note might work. An octave might also work to distinguish these.

> * `camera-shutter.oga` does not play when I take a screenshot. Instead I still hear the default sound which sounds like a film camera with an automatic film advance. Could just be another one of the Gnome sound trigger bugs.

This is 100% a bug in GNOME

> * Bell sound is good.
> * Volume up/down/mute sound is good.
> * Device add & device remove sound very good to me, but I will point out their similarity to the Windows 7 device add / remove sound effects (example here: https://youtu.be/vJmeYfbP0HU?t=45 ). This was already discussed and it sounds intentional, but I still thought it was worth pointing out.

This was indeed an intentional choice, as the general composition of these sounds is already widely recognized as device-insert and device-remove sounds. As a UX consideration, this helps to confirm that the device is working correctly. I believe the original sounds are short enough not to qualify as a unique composition, and since the actual sounds themselves are distinct sounding (only the notes themselves are similar), I don't think this causes issues.

Yaru and previous Ubuntu sound schemes also use similar sounds for these cues.

**Pull request merged**
