### PR TITLE
fix(apps): Tweaks to improve the Firefox tab line color in Groovy

### PR DESCRIPTION
**Pull request by isantop**
This unfortunately affects all of Firefox, so we also darken the color so enable
it to have somewhat acceptable contrast. It is confined to Firefox though.

DO NOT DELETE THIS BRANCH AFTER MERGING, as the same branch is going into #513 and #515

### CODE REVIEW

**Comment by jacobgkau** [comment]
This gets the accent colors back. Contrast seems like it might be a little too low in the dark theme:

Screenshot from 2021-04-20 16-04-10

Screenshot from 2021-04-20 16-04-58

GNOME Contrast puts it around a 1.6:1 contrast ratio, where the light theme's at a more acceptable 3.3:1. Can contrast be improved further in the dark theme?

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Our GNOME Terminal theme uses the light theme's highlight background (#48b9c7) against a white foreground color for highlighted text, and the web content portion of Firefox already uses the light theme instead of the dark theme, so if we were to use the light theme's highlight background within Firefox even in the dark theme, that would not be unprecedented.

**Comment by isantop** [comment]
@jacobgkau I set the background color to #48b9c7 as you suggested. The contrast is a bit iffy, but that was definitely not an okay contrast in the dark theme with the previous color.

**Review by jacobgkau — APPROVED** [review]
Doesn't "pop" quite as much in the dark theme, but legibility is better:

dark

light

Tested on Hirsute, Groovy, and Focal.

**Pull request merged**
