### PR TITLE
fix(sounds): add alarm-clock-elapsed sound

### LINKED ISSUE #473: [sound] Replace alarm-clock-elapsed
**Describe the problem:**
The freedesktop sound theme file for "alarm-clock-elapsed" is played when evolution-alarm-notify triggers for an event. Unfortunately, this file is rather obnoxious. At the very least, could we symlink `bell.oga` to `alarm-clock-elapsed`?

https://cgit.freedesktop.org/sound-theme-freedesktop/tree/stereo/alarm-clock-elapsed.oga

**Steps to reproduce:**
1.` canberra-gtk-play -i alarm-clock-elapsed`

**Distribution:**
PRETTY_NAME="Pop!_OS 20.04 LTS"

**Pop version:**
```
apt policy pop-gtk-theme | grep -i installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

  Installed: 5.2.0~1599689740~20.04~11b9d22
```

```
Pop Gtk theme - Pop Gtk theme used by System76

          ID: org.gtk.Gtk3theme.Pop
         Ref: runtime/org.gtk.Gtk3theme.Pop/x86_64/3.22
        Arch: x86_64
      Branch: 3.22
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1.6 MB

      Commit: bf0014cc176fe2a66eb69045bc3ed80663e09240dda1db97b5394ba3a501bea3
      Parent: 6154d9636034f0866dc7a2a08815931c641298ccfe1f5dd180875f4a4cb20f03
     Subject: Fix build issue (9d2c3d49)
        Date: 2019-10-22 21:52:03 +0000
```

### PR DESCRIPTION
**Pull request by isantop**
Played when an alarm clock in GNOME Clocks finishes.

Fixes #473

### CODE REVIEW

**Comment by isantop** [comment]
For testing this change, install GNOME Clocks (if it isn't already) and add an alarm to go off in a short time. When the alarm goes off, it should play the new sound.

**Comment by jacobgkau** [comment]
I'm not hearing the new sound in GNOME Clocks after installing this update and rebooting. I'm still hearing the old high-pitched alarm clock sound. (I do have the file installed in `/usr/share/sounds/Pop`, my sound theme is set to Pop, and other Pop sounds are working.)

**Comment by isantop** [comment]
@jacobgkau I'm not experiencing that here. With the theme version `5.3.1~1605830330~20.10~401addd` installed, the alarm clock is playing the new sound, even after a reboot.

Can you confirm the version you have installed using `apt policy pop-sound-theme` so I can investigate that further?

**Review by jacobgkau — APPROVED** [review]
```
system76@pop-os:~$ apt policy pop-sound-theme
pop-sound-theme:
  Installed: 5.3.1~1605830330~20.10~401addd
  Candidate: 5.3.1~1605830330~20.10~401addd
  Version table:
 *** 5.3.1~1605830330~20.10~401addd 1002
       1002 http://apt.pop-os.org/staging/alarm-clock-sound groovy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/alarm-clock-sound groovy/main i386 Packages
        100 /var/lib/dpkg/status
     5.3.0~1605227705~20.10~50f789b 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
     5.2.0~1586289568~20.04~f35b83b~ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe i386 Packages
```

Hmm. Revisiting this, I'm now getting the correct sound on the computer I was using to test last week, but I saw the same issue after updating a different computer. It looks like the sound updates if I delete `~/.cache/event-sound-cache.tbd.<long string>` and _then_ reboot.

I'll approve since it seems to be a user-level caching thing. I found https://specifications.freedesktop.org/sound-theme-spec/sound-theme-spec-latest.html saying:

> After installing/updating a sound in a theme directory, make sure to update the mtime of the theme directory itself (i.e. touch $XDG_DATA_DIRS/sounds/freedesktop or similar), so that caches can be kept up-to-date.

But it looks like the mtime on `/usr/share/sounds/Pop` was already being updated, and touching it again doesn't make the cache expire.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
