### PR TITLE
Add a text-shadow to Nautilus Desktop items

### PR DESCRIPTION
**Pull request by isantop**
Adds a text shadow to the Nautilus Desktop text, and makes it white by default.

### CODE REVIEW

**Comment by brs17** [comment]
@jackpot51 How does this look to you?

Without this patch (before):
before1
before2
before3


With patch:

after1
after2
after3

**Comment by WatchMkr** [comment]
@isantop @brs17 Better but can be improved. Please compare to adwaita.

**Comment by brs17** [comment]
Here are similar screenshots with Adwaita application and icon themes.

adwaita1
adwaita2
adwaita3

**Comment by isantop** [comment]
How about a border?

screenshot from 2018-10-22 11-42-12

**Comment by isantop** [comment]
Adwaita's shadow, to my eye, is harder to read than with the patch since it only has contrast on the left. An outline best solves this problem from a usability perspective.

**Comment by WatchMkr** [comment]
@isantop I think you're right. Let's use the border.

**Pull request merged**
