### PR TITLE
Install Plank theme

### LINKED ISSUE #67: Actually install the plank theme
We added a plank theme, but it's not being installed.

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #67

### CODE REVIEW

**Comment by isantop** [comment]
Any chance you have have this stuff added to the makefile instead? That way it won't get overwritten again.

**Comment by isantop** [comment]
I'm going to close this PR for now, since it's very old and likely won't apply cleanly anymore.

**Comment by cassidyjames** [comment]
1. This still applies cleanly as you can see in the diff view
2. Following the conventions of the existing code, the install.sh file appears to be the correct place to copy assets from the working directory to the system

How would you recommend I add it to the Makefile otherwise?

**Comment by cassidyjames** [comment]
Explicitly a bit verbose in case we want to make a compact plank theme, light variant, etc.

**Comment by isantop** [comment]
They will apply cleanly to master, but not against Version 3, which will be master within a few hours. The install.sh script is deleted from that branch, which will cause #67 again.

**Comment by cassidyjames** [comment]
In that case ask me to PR it against `version-3` as the Makefile has massively changed and the changes there won't apply cleanly, either.

**Pull request closed without merging**
