### PR TITLE
168 pop theme display

### LINKED ISSUE #168: Pop themes aren't displayed in the GtkInspector's drop down menu
**Distribution:** Tested on Fedora 28 & Ubuntu 18.04

**Gtk+ 3.0 version:** 3.22.30

**Desktop environment:** GNOME Shell 3.28.2

**Pop version:** 3.1.1

**Related Application and/or Shell theming (or name of widget)**

All GTK3 apps

**Actual issue**

Pop themes aren't displayed in the GtkInspector's drop down menu.

image

**Steps to reproduce**

1. Run: `GTK_DEBUG=interactive gtk3-widget-factory`
2. Go to "Visual" tab.
3. Click the combo button of "GTK+ Theme".

**Expected behavior**

Pop themes should be displayed in the GtkInspector's drop down menu.

**Behavior in Adwaita**

Adwaita is properly displayed in the drop down menu.

**Other Note (feature-request, question, etc...)**

It seems it's because there is no `gtk-3.0/` in `/usr/share/themes/Pop*/`. I think `gtk-3.20/` needs to be installed as `gtk-3.0/`.

For quick testing:

```sh
sudo mv /usr/share/themes/Pop/gtk-{3.20,3.0}
```

### PR DESCRIPTION
**Pull request by isantop**
In version 3.1.1, none of the Pop themes are listed in the theme selector dropdown in the Gtk Inspector. This can make debugging the theme somewhat cumbersome. As pointed out by @nana-4 , this was due to the theme folders not including a `gtk-3.0` subfolder, in our case symlinked to the latest `gtk-3.x` subfolder (to retain the fully-versioned qualities of the theme). 

This PR adjusts the build system to install these symlinks and fix the issue.

Fixes #168 

Note: To test that the themes are properly displayed in the inspector, install the `libgtk-3-dev` package, then run `GTK_DEBUG=interactive gtk3-widget-factory` to open the widget tester with the inspector open. From there, click the visual tab and change the GTK+ Theme box to one of the other Pop theme variants. Ensure that the variant is correctly applied and that the theme updates accordingly. Also ensure that all 6 variants are listed in the dropdown box.

### CODE REVIEW

**Comment by brs17** [comment]
screenshot from 2018-06-12 16-13-10

**Comment by isantop** [comment]
@brs17 Did you restart the widget-factory application after installing the updated theme? The themes available are loaded once on application start.

**Comment by brs17** [comment]
I've rebooted @isantop

**Comment by isantop** [comment]
I can't replicate that here.

**Comment by brs17** [comment]
```
total 68
-rw-r--r-- 1 root root 18092 jun 13 10:16 COPYING
drwxr-xr-x 4 root root  4096 jun 11 11:33 gnome-shell
drwxr-xr-x 3 root root  4096 jun 13 13:23 gtk-2.0
lrwxrwxrwx 1 root root   123 jun 13 10:16 gtk-3.0 -> /build/pop-gtk-theme-afolWX/pop-gtk-theme-3.1.2~1528906619~18.04~0f87eb6/debian/pop-gtk-theme/usr/share/themes/Pop/gtk-3.18
drwxr-xr-x 2 root root  4096 jun 13 13:23 gtk-3.20
drwxr-xr-x 2 root root  4096 jun 13 13:23 gtk-3.22
drwxr-xr-x 3 root root  4096 jun 11 11:33 gtk-common
-rwxr-xr-x 1 root root   205 jun 13 10:16 index.theme
drwxr-xr-x 2 root root  4096 jun 13 13:23 metacity-1
drwxr-xr-x 2 root root  4096 jun 13 13:23 plank
drwxr-xr-x 3 root root 12288 jun 13 13:23 xfwm4
```

**Comment by isantop** [comment]
Okay, I see what the issue is.

**Comment by isantop** [comment]
@brs17 fca031bd55d119301545f09a2cb74df833b318bf should work correctly now.

**Pull request merged**
