### PR TITLE
Copy elementary palette

### LINKED ISSUE #236: Ship elementary palette definitions
elementary is leaning more on the palette color definitions in the stylesheet to keep the colors in sync across the OS. What this means for Pop!_OS is that without the color palette defined, you'll start seeing funkiness like this:

image

instead of this:

appcenter-categories-after 2x

### PR DESCRIPTION
**Pull request by cassidyjames**
Adds the elementary color palette to the Granite folder i.e. so instead of this:

image 12

…you get this:

screenshot from 2018-11-09 15 24 32

Fixes #236

### CODE REVIEW

**Comment by isantop** [comment]
Thanks for addressing!

**Comment by brs17** [comment]
@isantop /@mmstick this will also need to be added to master_bionic

**Comment by brs17** [comment]
Well somehow after adding https://github.com/pop-os/shop/pull/107 and then building https://github.com/cassidyjames/pop-gtk-theme/tree/elementary-palette from scratch, this is what I get:
shop

That is a screenshot having scrolled down. I notice that "Accessories" is illegible.  What did I do wrong?

**Comment by brs17** [comment]
Instructions to replicate (on fresh install of Pop!_OS 18.10):
1. Add https://github.com/pop-os/shop/pull/107
2. Clone https://github.com/cassidyjames/gtk-theme
3. Checkout elementary-palette
4. `sudo apt install libtool pkg-config sassc inkscape optipng parallel libglib2.0-dev libgdk-pixbuf2.0-dev librsvg2-dev libxml2-utils`
5. `make clean`
6. `make`
7. `sudo make install`
8. Reboot
9. Launch pop-shop

**Comment by isantop** [comment]
@brs17 I updated our copy of the branch and pushed. It should build for us soon and we can test better.

**Comment by isantop** [comment]
Figured out the issue.

Categories are having their foreground color set to `@fg_color`, which also isn't defined in the theme (the GTK+ Standard named-color is `@theme_fg_color`). Adding that to the file has fixed the issue.

@cassidyjames If you pull git@github.com:pop-os/gtk-theme cassidyjames-elementary-palette into your branch and update, the build should complete and should enable this to be tested and merged.

**Pull request closed without merging**
