### PR TITLE
fix: cleanup some theme-parsing errors caused by outdated styling

### PR DESCRIPTION
**Pull request by isantop**
Removes a couple of outdated styling lines that we don't use anymore. They weren't being parsed anyway and shouldn't cause issues removing the, and will correct a couple of error messages due to theme parsing.

### CODE REVIEW

**Review by Absolucy — APPROVED** [review]
Can confirm that this does, in fact, get rid of the warnings I reported.

I'd prefer if someone else with more familiarity with the theme review this too, though.

**Review by leviport — CHANGES_REQUESTED** [review]
I'm seeing a slight problem with this PR. It seems to change the color of the top bar.

Before:
Screenshot from 2022-01-10 13-53-56

After:
Screenshot from 2022-01-10 13-54-32

I'll continue testing, but wanted to share this right away.

**Comment by 13r0ck** [comment]
@leviport that was because of #34 and its related cosmic-workspaces issue. I updated this branch with master so the issue should be fixed now.

**Comment by leviport** [comment]
Aha, I had forgotten about that. Thanks @13r0ck!

**Review by leviport — APPROVED** [review]
Yep, this fix is looking good to me now.

**Pull request merged**
