### PR TITLE
Version 3.1.0

### LINKED ISSUE #125: Minimize & Maximize Button
**Reporter info**

 * Distribution

Distributor ID:	Ubuntu
Description:	Pop!_OS 17.10 (Artful Aardvark)
Release:	17.10
Codename:	artful

 * Gtk+ 3.0 version

Installiert:           3.22.306-1ubuntu1
  Installationskandidat: 3.22.306-1ubuntu1
  Versionstabelle:
 *** 3.22.306-1ubuntu1 500
        500 http://ppa.launchpad.net/gnumdk/lollypop/ubuntu artful/main amd64 Packages

 * Desktop environment

Gnome Shell

 * Pop version

Pop!_GTK+ Version 3.0.2

**Related Application and/or Shell theming (or name of widget)**

All Pop Themes on CSD applications

**Actual issue**

The minimize and maximize buttons aren't round on applications with CSD, they are round for example on the terminal.
bildschirmfoto von 2018-03-07 11-33-37

**Steps to reproduce**

Open Gnome-Tweak-Tool and activate the minimize and maximize buttons.
Open an application with CSD like Nautilus and hover over the buttons.

**Expected behavior**

The buttons should be round as in non CSD applications.
bildschirmfoto von 2018-03-07 11-57-44

### LINKED ISSUE #129: Light variant has low contrast
The foreground text and icon color (i.e. in headerbars) is super low contrast with the background color, not even passing WCAG AA.

screenshot from 2018-03-23 11-21-22

### PR DESCRIPTION
**Pull request by isantop**
This PR merges Pop_Gtk version 3.1.0 into master. This version includes the following fixes and improvements:

* Makes sure that all titlebar buttons are the same size, and that `.rounded ` ones are actually round. (fixes #125 et al)
* Improves the contrast of the -light theme variant, particularly with regard to the titlebars and headerbars (Fixes #129 ).
* Makes the main background colors in the -dark variant more neutral.
* Improves the background color selections to ensure that different widgets have different colors, aiding usability by providing visual distinction between elements.

### CODE REVIEW

**Comment by cassidyjames** [comment]
Installed this locally, and it looks like the GTK2 theme is borked

screenshot from 2018-03-27 10-21-24

**Comment by isantop** [comment]
Looks like an assets-generation issue to me. What are the contents of your src/gtk-2.0/assets folder?

**Comment by drakkan** [comment]
the latest release on github

https://github.com/pop-os/gtk-theme/releases

is 3.0.0 R4, do you plan to add new releases here too? Or do we have to download debs from the below link?

http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-gtk-theme/

thanks

**Comment by isantop** [comment]
@drakkan Launchpad and the PPA will always have the latest version of the .deb packages. I'll throw together a tag here once we're at a good place for 3.1.0

**Pull request merged**
