### PR TITLE
Also apply styling to the widget designated as .terminal

### PR DESCRIPTION
**Pull request by mmstick**
Required by https://github.com/pop-os/installer/pull/137

### CODE REVIEW

**Comment by mmstick** [comment]
Testing involves testing the changes in https://github.com/pop-os/installer/pull/137. If the text in the terminal view has a dark margin, it worked. If it does not have a margin, it did not.

**Comment by brs17** [comment]
Before(with just https://github.com/pop-os/installer/pull/137 applied):
screenshot from 2018-06-26 14-36-58

After (adding this pr):
screenshot from 2018-06-26 14-52-13

If this is the expected functionality/look, then this is good to go.

**Comment by mmstick** [comment]
@brs17 Yep, that is what is expected.

**Comment by brs17** [comment]
Just took a look at it again after conflicts were resolved.

Noticed that when I put the mouse over the scrollbar the dark background turns white. I don't think that is expected

screenshot from 2018-06-26 15-45-09

**Comment by isantop** [comment]
Gotta love CSS cascades.

**Pull request merged**
