### PR TITLE
Pop! GTK 4.2

### LINKED ISSUE #302: Wonky theming for 'when' status in nautilus search
Distribution (run cat /etc/os-release):
Pop!_OS 19.04

Gtk+ 3.0 version - (run apt policy libgtk-3-0):
3.24.8-1ubuntu1

Desktop environment:
Gnome 3.32

Pop version (run apt policy pop-gtk-theme):
4.1.4155612098419.04~2988243

Related Application and/or Shell theming (or name of widget)
Nautilus

Actual issue
With the Pop GTK theme, if you perform a nautilus search using one of the 'when' options, the theming looks really out of place (see attached screenshot where it says 'since 5 days ago', poor contrast on the X button, label slightly overlapping with bottom of the search bar etc...)

Steps to reproduce:
Open Nautilus

Click the Search Icon

Click the dropdown arrow to the right of the search bar

Under 'When' click the dropdown and select a date range (e.g. 5 days ago)

search-theming

### LINKED ISSUE #303: Calendar event title color doesn't get inverted on light event background
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Installed: 3.22.30-1ubuntu3
  Candidate: 3.22.30-1ubuntu3
  Version table:
 *** 3.22.30-1ubuntu3 100
        100 /var/lib/dpkg/status
     3.22.29-3ubuntu1 500
        500 http://mirrors.neterra.net/ubuntu bionic/main amd64 Packages

**Desktop environment:**
GNOME 3.28.2

**Pop version (run ```apt policy pop-gtk-theme```):**
pop-gtk-theme:
  Installed: 4.1.4~1557754575~18.04~952b012
  Candidate: 4.1.4~1557754575~18.04~952b012
  Version table:
 *** 4.1.4~1557754575~18.04~952b012 500
        500 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        500 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main i386 Packages
        100 /var/lib/dpkg/status

**Related Application and/or Shell theming (or name of widget)**
This is the default ubuntu Calendar application. In Tweaks I have chosen Pop-slim-dark.

**Actual issue**
I'm using the default Calendar application and pulling my events from the Google Calendar. The event titles apparently use white color no matter if the contrast ratio is enough to ensure readability. For example, if the event has a yellow background the title is practically indistinguishable from it.

**Steps to reproduce**
Just use Tweaks to enable Pop-slim-dark (go to the Appearance tab and choose it from the Applications dropdown menu in the Themes section). Then import your events in the Calendar application and if you are using a light background color for specific events, you wouldn't be able to read the event title.

Slightly censored but descriptive image below:
Screenshot from 2019-05-23 14-52-22

**Expected behavior**
I humbly expect the color of the event title to switch to black when a certain contrast ratio threshold with the event background is reached. 

**Behavior in Adwaita**
The light Adwaita shows the expected behavior as described above, but the dark one doesn't.

**Other Note (feature-request, question, etc...)**
You guys are doing a great job! Thanks for making Linux even more visually appealing!

### LINKED ISSUE #304: Dark theme has an issue with menu items
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

aaronhoneycutt@pop-os ~> cat /etc/os-release
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

aaronhoneycutt@pop-os ~> apt policy libgtk-3-0
libgtk-3-0:
  Installed: 3.24.8-1ubuntu1
  Candidate: 3.24.8-1ubuntu1
  Version table:
 *** 3.24.8-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

GNOME 3.32

**Pop version (run ```apt policy pop-gtk-theme```):**

aaronhoneycutt@pop-os ~> apt policy pop-gtk-theme
pop-gtk-theme:
  Installed: 4.1.4~1557754575~19.04~952b012
  Candidate: 4.1.4~1557754575~19.04~952b012
  Version table:
 *** 4.1.4~1557754575~19.04~952b012 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
        100 /var/lib/dpkg/status

**Related Application and/or Shell theming (or name of widget)**

Dark Pop Theme

**Actual issue**

If you select a menu item in Setting or GNOME Tweaks then click away the background for the item doesn't come back until you click on it.

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

Does not happen in Adwaita.

**Other Note (feature-request, question, etc...)**

### LINKED ISSUE #305: GNOME Todo: Pop Variant: Difficult to Distinguish Delete Button
Seems to be a quirk in GNOME ToDo's styling. The color of the "Rename" and "Delete" buttons when selecting task lists remains the same in both the dark and light theme, making the buttons readable on the dark theme, but less readable in a lighter theme.

Screenshot from 2019-05-30 13-59-45

### LINKED ISSUE #306: Broken drop-down bar in Epiphany/Gnome Web in full-screen
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Installed: 3.24.8-1ubuntu1
  Candidate: 3.24.8-1ubuntu1
  Version table:
 *** 3.24.8-1ubuntu1 500
        500 http://it-mirrors.evowise.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status

**Pop version (run ```apt policy pop-gtk-theme```):**

  Installed: 4.1.4~1557754575~19.04~952b012
  Candidate: 4.1.4~1557754575~19.04~952b012
  Version table:
 *** 4.1.4~1557754575~19.04~952b012 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
        100 /var/lib/dpkg/status

**Actual issue**

Enter full-screen mode in Epiphany with F11. The drop-down bar and buttons are all transparent and illegible. Only the url field is not transparent. This does not happen on any other theme but the Pop variants.

**Behavior in Adwaita**
The drop-down bar in full-screen is perfectly consistent with the normal bar.

**Other Note (feature-request, question, etc...)**

Also, the blue loading bar on the url (not in full-screen) has poor visibility.

### LINKED ISSUE #309: feedreader: GtkSearchEntry in GtkHeaderBar
This may also be an issue. The search entry in a header bar does not have padding.

Screenshot from 2019-06-06 10-10-54

### PR DESCRIPTION
**Pull request by isantop**
Pop! GTK 4.2 brings a totally redesigned dark theme that greatly improves contrast and visual appearance by lightening many of the colors while simultaneously darkening and neutralizing backgrounds. As a result, text can be made slightly dimmer while still improving contrast, increasing readability and decreasing eye strain. 

There is also a new look for the shadows within the theme. Shadows no longer grow in size on hover, which helps to prevent shadow-overrun issues within the theme. Additionally, clicked buttons and elements now get pushed through the background, adding to the sense of depth and increasing recognition that an item has been activated.

Rounding out the changes are vast improvements to the light-titlebar Pop-Light variant (and slim mode). The appearance of the orange selection against the medium-light grey titlebar has been greatly enhanced by popping elements like buttons out from the surface of the titlebar and lightening their backgrounds. The result is a clean, modern, and light-feeling appearance while echoing the dimension and depth within the UI that makes Pop! pop!

Bugfixes in this release: 

Fixes #304 
Fixes #306 
Fixes #305 
Fixes #309 
Fixes #303 
Fixes #302

### CODE REVIEW

**Comment by isantop** [comment]
This contains new colors as directed by Kate to better fit with our new color branding guidelines.

**Comment by isantop** [comment]
@mmstick Minor change, which should ensure the contrast with colored text (like in your comment) is much better.

**Comment by isantop** [comment]
That firefox close button color still didn't change, but that's an issue for another time.

**Comment by mmstick** [comment]
The Firefox close button has been working on my end.

Screenshot from 2019-06-14 11-30-08

**Comment by isantop** [comment]
The backdrop state when the titlebar is integrated with the tab bar is wrong. Since that's a non-standard configuration, I think it's fine not to worry about that for now.

**Comment by JamesSwift** [comment]
After applying the package, my firefox scroll bar disappears. Reverting to the current package restores it.

pop
pop orig

**Comment by isantop** [comment]
@JamesSwift I'm not able to reproduce that here.

**Comment by JamesSwift** [comment]
Hmm. I'll try it again later, but for now I see form the image I was using the thin variant. Does that make a difference?

**Comment by JamesSwift** [comment]
Hi. Just tried again. After I install the update, then reboot, the scrollbar in Firefox disappears. I made no other changes between those steps. I will check in a fresh user account to, if it is any different I will report back.

**Comment by JamesSwift** [comment]
The plot thickens. Testing on a new user account, I experience the same affect: invisible (but still clickable) scroll-bar. However, when I use gnome-tweaks to change the theme to Adwaita... the scroll-bar is still invisible. Which is weird. Is there some other change in the pop-gtk-theme package other than to the pop theme?

**Comment by isantop** [comment]
There are no other changes from this PR other than to the theme. It sounds like you might have an issue with Firefox if the scrollbar is missing.

**Comment by JamesSwift** [comment]
But twice now It has vanished after installling the updated theme, then
reappeared after reverting to the current package. Seems to be connected.

**Comment by isantop** [comment]
@brs17 Please make a note to double check the visibility of scrollbars in Firefox when you test this PR. 

Thanks!

**Comment by rstrube** [comment]
I can confirm that scrollbar indicator is missing for Firefox.  The entire scrollbar is just white.

image

The scrollbar indicator on Chrome is visible.

image

**Comment by isantop** [comment]
@mmstick @brs17 I discovered some bugs with this pull request that have been patched as of ec6030c

**Comment by isantop** [comment]
There were some bugs I found while waiting on this pull request which have been patched as of 994ba01

**Comment by isantop** [comment]
I also managed to reproduce the firefox scrollbar issue as reported by @rstrube and @JamesSwift , and have corrected that issue in 2c639d4

**Comment by leviport** [comment]
There are a lot of color palette changes in this pr which seem to be too drastic of a change in the middle of a release. This overhaul should probably wait for 19.10. Let's also have the smaller issue fixes broken out into smaller individual PR's so they can be tested and deployed with more granularity and we can get them out before 19.10.

**Pull request closed without merging**
